name: erp_hvr_poc
description: ''
version: '0.1'
author: null
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: erphvrpoc
  parentArtefactID: santoshcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-07-26 17:06:54'
pipelines:
  pipelines/pl_sap_hvr_ingest:
    name: pl_sap_hvr_ingest
    description: ''
    author: santosh@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-07-26 17:09:34'
    datasets:
      inputs:
      - datasets/ds_bkpf_tbl
      - datasets/ds_hvr_bkpf
      - datasets/ds_hvr_rbkp
      - datasets/ds_hvr_rseg
      - datasets/ds_rbkp_tbl
      - datasets/ds_rseg_tbl
      - datasets/ds_silver_bkpf_tbl
      - datasets/ds_silver_rbkp_tbl
      - datasets/ds_silver_rseg_tbl
      outputs:
      - datasets/ds_bkpf_tbl
      - datasets/ds_gold_invoices_csv
      - datasets/ds_gold_invoices_tbl
      - datasets/ds_rbkp_tbl
      - datasets/ds_rseg_tbl
      - datasets/ds_silver_bkpf_tbl
      - datasets/ds_silver_rbkp_tbl
      - datasets/ds_silver_rseg_tbl
    subgraphs: []
    dependencies: {}
  pipelines/pl_load_postgres_synth:
    name: pl_load_postgres_synth
    description: ''
    author: santosh@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-07-27 03:44:20'
    datasets:
      inputs:
      - datasets/ds_cdc_file
      outputs:
      - datasets/ds_postgres_hvr
    subgraphs: []
    dependencies: {}
  pipelines/pl_sap_hvr_hist_load:
    name: pl_sap_hvr_hist_load
    description: null
    author: santosh@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-07 15:47:52'
    datasets:
      inputs:
      - datasets/ds_bkpf_tbl
      - datasets/ds_hvr_bkpf
      - datasets/ds_hvr_rbkp
      - datasets/ds_hvr_rseg
      - datasets/ds_rbkp_tbl
      - datasets/ds_rseg_tbl
      - datasets/ds_silver_bkpf_tbl
      - datasets/ds_silver_rbkp_tbl
      - datasets/ds_silver_rseg_tbl
      outputs:
      - datasets/ds_bkpf_tbl
      - datasets/ds_gold_invoices_csv
      - datasets/ds_gold_invoices_tbl
      - datasets/ds_rbkp_tbl
      - datasets/ds_rseg_tbl
      - datasets/ds_silver_bkpf_tbl
      - datasets/ds_silver_rbkp_tbl
      - datasets/ds_silver_rseg_tbl
    subgraphs: []
    dependencies: {}
datasets:
  datasets/ds_sap_bkpdf:
    name: ds_sap_bkpdf
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-07-26 17:28:33'
    mode: batch
    physicalDatasets:
      fab_fivetran_Prophecy:
        fabricId: 11820
        datasetType: Database
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-07-26 17:28:33'
  datasets/ds_hvr_bkpf:
    name: ds_hvr_bkpf
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-07-26 17:33:50'
    mode: batch
    physicalDatasets:
      fab_fivetran_Prophecy:
        fabricId: 11820
        datasetType: File
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-07-26 17:33:50'
  datasets/ds_bkpf_tbl:
    name: ds_bkpf_tbl
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-07-26 17:37:58'
    mode: batch
    physicalDatasets:
      fab_fivetran_Prophecy:
        fabricId: 11820
        datasetType: Database
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-07-26 17:37:58'
  datasets/ds_cdc_file:
    name: ds_cdc_file
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-07-26 18:00:53'
    mode: batch
    physicalDatasets:
      fab_fivetran_Prophecy:
        fabricId: 11820
        datasetType: File
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-07-26 18:00:53'
  datasets/ds_postgres_hvr:
    name: ds_postgres_hvr
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-07-26 18:25:51'
    mode: batch
    physicalDatasets:
      fab_fivetran_Prophecy:
        fabricId: 11820
        datasetType: Warehouse
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-07-26 18:25:51'
  datasets/ds_hvr_rbkp:
    name: ds_hvr_rbkp
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-07-27 03:59:22'
    mode: batch
    physicalDatasets:
      fab_fivetran_Prophecy:
        fabricId: 11820
        datasetType: File
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-07-27 03:59:22'
  datasets/ds_rbkp_tbl:
    name: ds_rbkp_tbl
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-07-27 04:03:26'
    mode: batch
    physicalDatasets:
      fab_fivetran_Prophecy:
        fabricId: 11820
        datasetType: Database
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-07-27 04:03:26'
  datasets/ds_hvr_rseg:
    name: ds_hvr_rseg
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-07-27 04:09:24'
    mode: batch
    physicalDatasets:
      fab_fivetran_Prophecy:
        fabricId: 11820
        datasetType: File
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-07-27 04:09:24'
  datasets/ds_rseg_tbl:
    name: ds_rseg_tbl
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-07-27 04:14:01'
    mode: batch
    physicalDatasets:
      fab_fivetran_Prophecy:
        fabricId: 11820
        datasetType: Database
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-07-27 04:14:01'
  datasets/ds_silver_bkpf_tbl:
    name: ds_silver_bkpf_tbl
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-07-31 11:41:51'
    mode: batch
    physicalDatasets:
      fab_fivetran_Prophecy:
        fabricId: 11820
        datasetType: Database
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-07-31 11:41:51'
  datasets/ds_silver_rbkp_tbl:
    name: ds_silver_rbkp_tbl
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-07-31 13:46:13'
    mode: batch
    physicalDatasets:
      fab_fivetran_Prophecy:
        fabricId: 11820
        datasetType: Database
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-07-31 13:46:13'
  datasets/ds_silver_rseg_tbl:
    name: ds_silver_rseg_tbl
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-07-31 13:54:33'
    mode: batch
    physicalDatasets:
      fab_fivetran_Prophecy:
        fabricId: 11820
        datasetType: Database
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-07-31 13:54:33'
  datasets/ds_gold_invoices_tbl:
    name: ds_gold_invoices_tbl
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-07-31 14:21:18'
    mode: batch
    physicalDatasets:
      fab_fivetran_Prophecy:
        fabricId: 11820
        datasetType: Database
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-07-31 14:21:18'
  datasets/ds_gold_invoices_csv:
    name: ds_gold_invoices_csv
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-08-01 07:33:41'
    mode: batch
    physicalDatasets:
      fab_fivetran_Prophecy:
        fabricId: 11820
        datasetType: File
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-08-01 07:33:41'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-07-26 17:06:54'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-07-27T03:44:27.75633Z'
  name: plibMaven
  version: 8.0.29
  id: '1686340970'
  createdAt: '2024-07-27T03:44:27.75629Z'
- type: plibPypi
  modifiedAt: '2024-07-27T03:44:27.756416Z'
  name: plibPypi
  version: 1.9.9
  id: '977155637'
  createdAt: '2024-07-27T03:44:27.756406Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-07-26 16:50:25'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-07-26 16:50:25'
  '12656':
    projectUID: 12656
    projectName: ProphecyStreamingPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12656.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2024-08-08 04:43:39'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
