name: erp_hvr_poc2
description: ''
version: 0.0.1
author: santosh@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: erphvrpoc2
  parentArtefactID: santoshcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-08-24 15:58:30'
pipelines:
  pipelines/pl_sap_hvr_history_load:
    name: pl_sap_hvr_history_load
    description: ''
    author: santosh@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-24 15:58:30'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/pl_sap_hvr_ingest:
    name: pl_sap_hvr_ingest
    description: ''
    author: santosh@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-24 16:00:26'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-08-24 15:58:30'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-08-24T15:58:30.187328Z'
  name: plibMaven
  version: 8.0.31
  id: '857920181'
  createdAt: '2024-08-24T15:58:30.187328Z'
  type: plibMaven
- modifiedAt: '2024-08-24T15:58:30.187328Z'
  name: plibPypi
  version: 1.9.9
  id: '618002196'
  createdAt: '2024-08-24T15:58:30.187328Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.26
    isDefault: true
    author: null
    createdAt: '2024-08-24 15:57:51'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-08-24 15:57:51'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
